services:

  consul:
    command: -server -bootstrap
    image: gliderlabs/consul-server
    ports:
      - "8300"
      - "8400"
      - "8500:8500"
      - "53"
    healthcheck:
      test: [ "CMD", "wget", "-q", "-s", "http://127.0.0.1:8500/v1/status/leader" ]
      interval: 10s
      timeout: 10s
      retries: 12
      start_period: 40s

  nginx:
    image: openlmis/nginx:${OL_NGINX_VERSION}
    ports:
      - '80:80'
    env_file: settings.env
    environment:
      NGINX_LOG_DIR: '/var/log/nginx/log'
    volumes:
      - 'nginx-log:/var/log/nginx/log'
      - 'consul-template-log:/var/log/consul-template'
    depends_on:
      consul:
        condition: service_healthy

  reference-ui:
    restart: always
    image: openlmisgambia/ui:${GAMBIA_UI_VERSION}
    env_file: settings.env
    depends_on:
      consul:
        condition: service_healthy

  requisition:
    restart: always
    image: openlmis/requisition:${OL_REQUISITION_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx2048m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on:
      log:
        condition: service_started
      consul:
        condition: service_healthy

  referencedata:
    restart: always
    image: openlmis/referencedata:${OL_REFERENCEDATA_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx2048m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on:
      log:
        condition: service_started
      consul:
        condition: service_healthy

  auth:
    restart: always
    image: openlmis/auth:${OL_AUTH_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
    volumes:
      - 'service-config:/config'
      - 'auth-tomcat-log:/var/log/auth-tomcat'
      - 'syslog:/var/log'
    depends_on:
      log:
        condition: service_started
      consul:
        condition: service_healthy

  notification:
    restart: always
    image: openlmis/notification:${OL_NOTIFICATION_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on:
      log:
        condition: service_started
      consul:
        condition: service_healthy

  fulfillment:
    restart: always
    image: openlmis/fulfillment:${OL_FULFILLMENT_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx1024m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on:
      log:
        condition: service_started
      consul:
        condition: service_healthy

  cce:
    restart: always
    image: openlmis/cce:${OL_CCE_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx1024m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on:
      log:
        condition: service_started
      consul:
        condition: service_healthy

  stockmanagement:
    restart: always
    image: openlmis/stockmanagement:${OL_STOCKMANAGEMENT_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx2048m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on:
      log:
        condition: service_started
      consul:
        condition: service_healthy

  report:
    restart: always
    image: openlmisgambia/reports:${GAMBIA_REPORTS_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx2560m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on:
      log:
        condition: service_started
      consul:
        condition: service_healthy

  buq:
    restart: always
    image: openlmis/buq:${OL_BUQ_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx1024m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on:
      log:
        condition: service_started
      consul:
        condition: service_healthy

  diagnostics:
    restart: always
    image: openlmis/diagnostics:${OL_DIAGNOSTICS_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on:
      log:
        condition: service_started
      consul:
        condition: service_healthy

  log:
    restart: always
    image: openlmis/rsyslog:${OL_RSYSLOG_VERSION}
    volumes:
      - 'syslog:/var/log'
    depends_on:
      service-configuration:
        condition: service_started
      consul:
        condition: service_healthy

  service-configuration:
    build:
      context: config
    volumes:
      - service-config:/config

  ftp:
    image: driesva/proftpd
    ports:
      - "${OL_FTP_PORT_21:-21}:21"
      - "${OL_FTP_PORT_20:-20}:20"
    env_file: settings.env
    depends_on:
      consul:
        condition: service_healthy

  redis:
    image: redis:3.2.12
    depends_on:
      consul:
        condition: service_healthy

volumes:
  syslog:
  nginx-log:
  auth-tomcat-log:
  consul-template-log:
  service-config:
